name: Add Contributors from Issues

on:
    issues:
        types: [closed]

permissions:
    contents: write

jobs:
    add-contributors:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16"

            - name: Install all-contributors-cli
              run: npm install -g all-contributors-cli

            - name: Configure Git user
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"

            - name: Add Contributor
              run: |
                  all-contributors add ${{ github.actor }} code
                  all-contributors generate

            - name: Pull latest changes
              run: git pull origin main --rebase

            - name: Commit changes
              run: |
                  git add .
                  git commit -m "chore: update contributors" || echo "No changes to commit"
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
